package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/projectdiscovery/cloudlist/graph/model"
	"github.com/projectdiscovery/cloudlist/pkg/inventory"
	"github.com/projectdiscovery/cloudlist/pkg/schema"
)

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context) ([]*model.Asset, error) {
	inventory, err := inventory.New(schema.Options{})
	if err != nil {
		return nil, fmt.Errorf("failed to create inventory: %w", err)
	}

	var assets []*model.Asset
	for _, provider := range inventory.Providers {
		resources, err := provider.Resources(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get resources from provider %s: %w", provider.Name(), err)
		}

		for _, resource := range resources.Items {
			assets = append(assets, &model.Asset{
				Public:      resource.Public,
				Provider:    resource.Provider,
				Service:     resource.Service,
				ID:          resource.ID,
				PublicIpv4:  &resource.PublicIPv4,
				PublicIpv6:  &resource.PublicIPv6,
				PrivateIpv4: &resource.PrivateIpv4,
				PrivateIpv6: &resource.PrivateIpv6,
				DNSName:     &resource.DNSName,
				Metadata:    resource.Metadata,
			})
		}
	}

	return assets, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
