// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Asset struct {
	Public      bool           `json:"public"`
	Provider    string         `json:"provider"`
	Service     string         `json:"service"`
	ID          string         `json:"id"`
	PublicIpv4  *string        `json:"public_ipv4,omitempty"`
	PublicIpv6  *string        `json:"public_ipv6,omitempty"`
	PrivateIpv4 *string        `json:"private_ipv4,omitempty"`
	PrivateIpv6 *string        `json:"private_ipv6,omitempty"`
	DNSName     *string        `json:"dns_name,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type Query struct {
}
