# Use an official AWS CLI image
FROM amazon/aws-cli:2.4.11

# Copy the script into the container
COPY _docs/poc2/test/setup_aws_resources.sh /app/setup_aws_resources.sh

# Make the script executable
RUN chmod +x /app/setup_aws_resources.sh
